  services:
    raft:
      # build: .
      image: raft
      hostname: raft
      # ports:
        # - "4222:4222"
        # - "8222:8222"
        # - "6222:6222"
      networks:
        - nats
      depends_on:
        - nats
    nats:
      image: nats:latest
      expose:
        - "4222"
        - "8222"
        - "6222"
    #   ports:
    #     - "4222"
    #     - "8222"
    #     - "6222"
      networks:
        - nats

  networks:
    nats:
      driver: bridge

