  services:
    raft:
      # build: .
      image: "raft"
      hostname: "raft"
      networks:
        - "nats-network"
      depends_on:
        - "nats"
    nats:
      image: "nats:latest"
      hostname: "nats-server"
      expose:
        - "4222"
        - "8222"
        - "6222"
      networks:
        - "nats-network"
    

  networks:
    nats-network:
      driver: bridge

